/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package upb.sgttp.gui;

import java.util.function.Predicate;
import javax.swing.table.DefaultTableModel;
import jp.array.Array;
import jp.linkedlist.singly.LinkedList;
import upb.sgttp.model.domain.persons.AbstractPerson;
import upb.sgttp.model.domain.persons.Customer;
import upb.sgttp.model.domain.persons.Employee;
import upb.sgttp.model.domain.persons.User;
import upb.sgttp.model.domain.Luggage;
import upb.sgttp.model.domain.persons.Admin;
import upb.sgttp.model.domain.persons.Contact;

/**
 *
 * @author thewe
 */
public class UserManagement extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    LinkedList<User> list = new LinkedList<>();
    LinkedList<Customer> customers = new LinkedList();
    LinkedList<Employee> employees = new LinkedList();
    LinkedList<Admin> admins = new LinkedList();
    LinkedList<Contact> contacts = new LinkedList();

    /**
     * Creates new form UserManagement
     */
    public UserManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is alwaysz
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("gestion de usuarios");

        jButton3.setText("agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("dar de baja");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("prev");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Nombres");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellidos");

        jLabel4.setText("numeros");

        jLabel5.setText("Usuario");

        jLabel6.setText("Contraseña");

        jLabel7.setText("tipo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Empleado", "Admin", "Contact" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton1))
                                .addGap(26, 26, 26)
                                .addComponent(jButton4)
                                .addGap(29, 29, 29)
                                .addComponent(jButton5))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3)
                                .addComponent(jTextField4)
                                .addComponent(jTextField5))
                            .addComponent(jLabel7)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 509, Short.MAX_VALUE)))
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(116, 116, 116)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AdminPage ventanaPrincipal = new AdminPage();
        ventanaPrincipal.setVisible(true);
        ventanaPrincipal.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    public void addUsers() {
        model.addColumn("Nombres");
        model.addColumn("Apellidos");
        model.addColumn("Numeros");
        model.addColumn("usuario");
        model.addColumn("Contraseña");
        model.addColumn("tipo");
        model.addColumn("id");
        reloadTable();
    }

    private void reloadTable() {
        //borrar los elementos del modelo
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        list = upb.sgttp.model.domain.Main.getUsers();
        for (int i = 0; i < list.size(); i++) {
            AbstractPerson person = list.get(i).getPerson();
            String numbers = "";
            for (int j = 0; j < list.get(i).getPerson().getPhoneNumbers().size(); j++) {
                numbers += list.get(i).getPerson().getPhoneNumbers().get(j);
                if (j < list.get(i).getPerson().getPhoneNumbers().size() - 1) {
                    numbers += ",";
                }
            }
            Object u[] = new Object[7];
            u[0] = person.getNames();
            u[1] = person.getLastNames();
            u[2] = numbers;
            u[3] = list.get(i).getUsername();
            u[4] = list.get(i).getPassword();
            u[5] = list.get(i).getType();
            int tipo = list.get(i).getType();
            switch (tipo) {
                case 0://empleado
                    Employee empleado = (Employee) list.get(i).getPerson();
                    u[6] = empleado.getId();
                    break;
                case 1://cliente
                    Customer customer = (Customer) list.get(i).getPerson();
                    u[6] = customer.getCustomerId();
                    break;
                case 2://contact
                    Contact contact = (Contact) list.get(i).getPerson();
                    u[6] = contact.getContactId();
                    break;
                case 3://admin
                    Admin admin = (Admin) list.get(i).getPerson();
                    u[6] = admin.getId();
                    break;
            }
            model.addRow(u);
        }
        jTable1.setModel(model);
    }

    @SuppressWarnings("unchecked")
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sType = (String) jComboBox1.getSelectedItem();
        list = upb.sgttp.model.domain.Main.getUsers();
        String nombres = jTextField1.getText();
        String apellidos = jTextField2.getText();
        String numeros = jTextField3.getText();
        String[] numbers = numeros.split(",");
        String usuario = jTextField4.getText();
        String contraseña = jTextField5.getText();
//        @SuppressWarnings("rawtypes")
        if (!usuario.isBlank() || !contraseña.isBlank()) {
            Array array = new Array(numbers);
//            AbstractPerson person = new AbstractPerson(nombres, contraseña, array);
            int tipo = -1;
            if (sType.equals("Empleado")) {
                tipo = 0;
                Employee employ = new Employee(nombres, apellidos, array, upb.sgttp.model.domain.Main.createId(tipo));
                list.add(new User(employ, usuario, contraseña, tipo));
                employees.add(employ);
                upb.sgttp.model.domain.Main.modifyListEmployees(employees);
                upb.sgttp.model.domain.Main.modifyJsonEmployee(employees);
            } else {
                if (sType.equals("Cliente")) {
                    tipo = 1;
                    LinkedList luggage = new LinkedList<>(Luggage.getNullLuggage());
                    Customer customer = new Customer(luggage, nombres, apellidos, array, upb.sgttp.model.domain.Main.createId(tipo));
                    list.add(new User(customer, usuario, contraseña, tipo));
                    customers.add(customer);
                    upb.sgttp.model.domain.Main.modifyJsonCustomer(customers);
                    upb.sgttp.model.domain.Main.modifyListCustomers(customers);
                } else {
                    if (sType.equals("Admin")) {
                        tipo = 3;
                        Admin admin = new Admin(nombres, apellidos, array, upb.sgttp.model.domain.Main.createId(tipo));
                        list.add(new User(admin, usuario, contraseña, tipo));
                        admins.add(admin);
                        upb.sgttp.model.domain.Main.modifyJsonAdmin(admins);
                        upb.sgttp.model.domain.Main.modifyListAdmins(admins);
                    } else {
                        if (sType.equals("Contact")) {
                            tipo = 2;
                            Contact contact = new Contact(nombres, apellidos, array, upb.sgttp.model.domain.Main.createId(tipo));
                            list.add(new User(contact, usuario, contraseña, tipo));
                            contacts.add(contact);
                            upb.sgttp.model.domain.Main.modifyJsonContact(contacts);
                            upb.sgttp.model.domain.Main.modifyListContacts(contacts);
                        }
                    }
                }
            }
//        list.add(new User(person, usuario, contraseña, tipo));
        }
        upb.sgttp.model.domain.Main.modifyJsonUser(list);
        upb.sgttp.model.domain.Main.modifyListUsers(list);

        reloadTable();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        System.out.println("selectedRow = " + selectedRow);
        System.out.println("list size = " + list.getSize());
        for (int i = 0; i < list.size(); i++) {
            System.out.println("list " + i + " :" + list.get(i).getType());
        }
        // Verificar si se ha seleccionado una fila
        if (selectedRow != -1) {
            // Eliminar la fila del modelo de la tabla
            if (list.size() > 1) {
                int tipo = list.get(selectedRow).getType();
                System.out.println("tipo = " + tipo);
                switch (tipo) {
                    case 0://empleados
                        Employee employee = (Employee) list.get(selectedRow).getPerson();
                        employees.remove(employee);
                        upb.sgttp.model.domain.Main.modifyListEmployees(employees);
                        upb.sgttp.model.domain.Main.modifyJsonEmployee(employees);
                        break;
                    case 1://cliente
                        Customer customer = (Customer) list.get(selectedRow).getPerson();
                        customers.remove(customer);
                        upb.sgttp.model.domain.Main.modifyListCustomers(customers);
                        upb.sgttp.model.domain.Main.modifyJsonCustomer(customers);
                        break;
                    case 2://contacto
                        Contact contact = (Contact) list.get(selectedRow).getPerson();
                        contacts.remove(contact);
                        upb.sgttp.model.domain.Main.modifyListContacts(contacts);
                        upb.sgttp.model.domain.Main.modifyJsonContact(contacts);
                        break;
                    case 3://admin
                        Admin admin = (Admin) list.get(selectedRow).getPerson();
                        admins.remove(admin);
                        upb.sgttp.model.domain.Main.modifyListAdmins(admins);
                        upb.sgttp.model.domain.Main.modifyJsonAdmin(admins);
                        break;
                }
                list.remove(list.get(selectedRow));
                upb.sgttp.model.domain.Main.modifyJsonUser(list);
                upb.sgttp.model.domain.Main.modifyListUsers(list);
                reloadTable();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        // Verificar si se ha seleccionado una fila
        if (selectedRow != -1) {
            // modificar la fila del modelo de la tabla
            list.get(selectedRow);
            String sType = (String) jComboBox1.getSelectedItem();
            list = upb.sgttp.model.domain.Main.getUsers();
            String nombres = jTextField1.getText();
            String apellidos = jTextField2.getText();
            String numeros = jTextField3.getText();
            String[] numbers = numeros.split(",");
            String usuario = jTextField4.getText();
            String contraseña = jTextField5.getText();
            Array array = new Array(numbers);
            System.out.println("selectrow:" + selectedRow);
            int tipo = -1;
            if (sType.equals("Empleado")) {
                tipo = 0;
                Employee employ = new Employee(nombres, apellidos, array, upb.sgttp.model.domain.Main.getEmployeeId(selectedRow));
                upb.sgttp.model.domain.Main.modifyEmployee(employ);
                list.get(selectedRow).setPerson(employ);
//                list.get(selectedRow).setUsername(usuario);
//                list.get(selectedRow).setPassword(contraseña);
//                list.get(selectedRow).setType(tipo);
//                upb.sgttp.model.domain.Main.modifyListUsers(list);
//                upb.sgttp.model.domain.Main.modifyJsonUser(list);
            } else {
                if (sType.equals("Cliente")) {
                    tipo = 1;
                    LinkedList luggage = new LinkedList<>(Luggage.getNullLuggage());
                    Customer customer = new Customer(luggage, nombres, apellidos, array, upb.sgttp.model.domain.Main.getCustomerId(selectedRow));
                    upb.sgttp.model.domain.Main.modifyCustomer(customer);
                    list.get(selectedRow).setPerson(customer);
                } else {
                    if (sType.equals("Admin")) {
                        tipo = 3;
                        Admin admin = new Admin(nombres, apellidos, array, upb.sgttp.model.domain.Main.getAdminId(selectedRow));
                        upb.sgttp.model.domain.Main.modifyAdmin(admin);
                        list.get(selectedRow).setPerson(admin);
                    } else {
                        if (sType.equals("Contact")) {
                            tipo = 2;
                            Contact contact = new Contact(nombres, apellidos, array, upb.sgttp.model.domain.Main.getContactId(selectedRow));
                            upb.sgttp.model.domain.Main.modifyContact(contact);
                            list.get(selectedRow).setPerson(contact);
                        }
                    }
                }
            }
            list.get(selectedRow).setUsername(usuario);
            list.get(selectedRow).setPassword(contraseña);
            list.get(selectedRow).setType(tipo);
            upb.sgttp.model.domain.Main.modifyListUsers(list);
            upb.sgttp.model.domain.Main.modifyJsonUser(list);
//            list.get(selectedRow).setPerson(person);
//            list.get(selectedRow).setUsername(usuario);
//            list.get(selectedRow).setPassword(contraseña);
//            list.get(selectedRow).setType(tipo);
//            upb.sgttp.model.domain.Main.modifyListUsers(list);
            reloadTable();
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
